Repository schubergphilis/terraform-aws-mcaf-avm, pull requests merged in 2024-08, with the labels that each got.

#57 breaking: set default auth mode from 'iam_user' to 'iam_role_oidc' and modify outputs
  README.md
  UPGRADING.md
  outputs.tf
  variables.tf
Labels: breaking

#55 feat: account variable set
  README.md
  main.tf
  outputs.tf
  variables.tf
Labels: feature

#59 fix: merge var.account_variable_set.clear_text_terraform_variables into local
  main.tf
Labels: bug

#60 fix: modify notification-settings behaviour to take "tfe_workspace" value
  main.tf
Labels: bug

#61 fix: resolving an error in the inheritance behaviour of `notification_configuration` and `team_access`
  README.md
  main.tf
  variables.tf
Labels: bug
