Repository schubergphilis/terraform-aws-mcaf-avm, pull requests merged in 2025-03, with the labels that each got.

#70 enhancement: bump aws-mcaf-workspace to 2.5.x
  examples/basic/terraform.tf
  main.tf
  terraform.tf
Labels: feature

#71 enhancement: Ignore terraform_version when "" is provided in var.additional_tfe_workspaces.terraform_version
  README.md
  main.tf
Labels: enhancement, feature

#72 fix: set default for var.tfe_workspace.set_working_directory to true
  README.md
  variables.tf
Labels: fix
